api-gateway:
  envs:
  - name: JVM_MEM
    value: 5g
  - name: ES_HOST
    value: localhost
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: "80.95.163.20,149.146.5.85,193.172.150.192/26,91.240.70.5,183.82.112.139,182.73.163.98,18.192.155.96,3.124.93.29"
    hosts:
      - host: apigw.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 9072
      - host: apigwis.kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 5555
      - host: kla-dev.dev-1.dip.ccs.nl
        paths:
          - path: /
            pathType: Prefix
            backend:
              servicePort: 5555
    tls:
      - hosts:
          - apigw.kla-dev.dev-1.dip.ccs.nl
        secretName: apigw-tls
      - hosts:
          - apigwis.kla-dev.dev-1.dip.ccs.nl
        secretName: apigwis-tls
      - hosts:
          - kla-dev.dev-1.dip.ccs.nl
        secretName: vpdev-tls