applications:
- name: "DIP AutTest - Dynamic Routing (L2P)"
  version: "1.0"
  consumingAPIs:
    _all: true
- name: "DIP AutTest - Dynamic Routing (Scope)"
  version: "1.0"
  consumingAPIs:
    _all: true
- name: "DIP AutTest - Dynamic Routing (Simple)"
  version: "1.0"
  consumingAPIs:
    _all: true
- name: "DIP AutTest - Node Routing"
  version: "1.0"
  consumingAPIs:
    _all: true