apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  valuesFrom:
  #common config
  - kind: ConfigMap
    name: globals-common-config
  - kind: ConfigMap
    name: api-gateway-common-config
  - kind: ConfigMap
    name: db-configurator-common-config
  - kind: ConfigMap
    name: db-initializer-common-config
  - kind: ConfigMap
    name: universal-messaging-common-config
  - kind: ConfigMap
    name: universal-messaging-configurator-common-config
  - kind: ConfigMap
    name: integration-server-common-config
  - kind: ConfigMap
    name: my-webmethods-server-common-config
  - kind: ConfigMap
    name: ewih-service-common-config
  - kind: ConfigMap
    name: process-service-common-config
  - kind: ConfigMap
    name: ldap-common-config
  - kind: ConfigMap
    name: memcached-common-config
  - kind: ConfigMap
    name: kie-server-common-config
  - kind: ConfigMap
    name: kie-workbench-common-config
  #static config
  - kind: ConfigMap
    name: globals-specific-config
  - kind: ConfigMap
    name: api-gateway-specific-config
  - kind: ConfigMap
    name: db-configurator-specific-config
  - kind: ConfigMap
    name: db-initializer-specific-config
  - kind: ConfigMap
    name: universal-messaging-specific-config
  - kind: ConfigMap
    name: universal-messaging-configurator-specific-config
  - kind: ConfigMap
    name: integration-server-specific-config
  - kind: ConfigMap
    name: my-webmethods-server-specific-config
  - kind: ConfigMap
    name: ewih-service-specific-config
  - kind: ConfigMap
    name: process-service-specific-config
  - kind: ConfigMap
    name: ldap-specific-config
  - kind: ConfigMap
    name: memcached-specific-config
  - kind: ConfigMap
    name: kie-server-specific-config
  - kind: ConfigMap
    name: kie-workbench-specific-config
  #promote config
  - kind: ConfigMap
    name: globals-promotable-config
  - kind: ConfigMap
    name: api-gateway-promotable-config
  - kind: ConfigMap
    name: db-configurator-promotable-config
  - kind: ConfigMap
    name: db-initializer-promotable-config
  - kind: ConfigMap
    name: universal-messaging-promotable-config
  - kind: ConfigMap
    name: universal-messaging-configurator-promotable-config
  - kind: ConfigMap
    name: integration-server-promotable-config
  - kind: ConfigMap
    name: my-webmethods-server-promotable-config
  - kind: ConfigMap
    name: ewih-service-promotable-config
  - kind: ConfigMap
    name: process-service-promotable-config
  - kind: ConfigMap
    name: ldap-promotable-config
  - kind: ConfigMap
    name: memcached-promotable-config
  - kind: ConfigMap
    name: kie-server-promotable-config
  - kind: ConfigMap
    name: kie-workbench-promotable-config