apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../specifics
configMapGenerator:
- behavior: merge
  envs:
  - envs/api-gateway-policies.properties
  name: api-gateway-policies
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-attachment.properties
  name: endpoint-db-attachment
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-cache.properties
  name: endpoint-db-cache
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-cs.properties
  name: endpoint-db-cs
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-drs.properties
  name: endpoint-db-drs
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-events.properties
  name: endpoint-db-events
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-ewih.properties
  name: endpoint-db-ewih
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-questionnaire-read.properties
  name: endpoint-db-questionnaire-read
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-questionnaire.properties
  name: endpoint-db-questionnaire
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-rcip.properties
  name: endpoint-db-rcip
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-db-wm.properties
  name: endpoint-db-wm
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-ip-ldap.properties
  name: endpoint-ip-ldap
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-is.properties
  name: endpoint-is
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-memcached.properties
  name: endpoint-memcached
  options:
    disableNameSuffixHash: true
- behavior: merge
  envs:
  - envs/endpoint-um.properties
  name: endpoint-um
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/api-gateway.yaml
  name: api-gateway-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/db-configurator.yaml
  name: db-configurator-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/db-initializer.yaml
  name: db-initializer-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/ewih-service.yaml
  name: ewih-service-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/globals.yaml
  name: globals-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/integration-server.yaml
  name: integration-server-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/kie-server.yaml
  name: kie-server-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/kie-workbench.yaml
  name: kie-workbench-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/ldap.yaml
  name: ldap-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/memcached.yaml
  name: memcached-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/my-webmethods-server.yaml
  name: my-webmethods-server-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/process-service.yaml
  name: process-service-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/universal-messaging-configurator.yaml
  name: universal-messaging-configurator-promotable-config
  options:
    disableNameSuffixHash: true
- behavior: create
  files:
  - values/universal-messaging.yaml
  name: universal-messaging-promotable-config
  options:
    disableNameSuffixHash: true
