apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 10m
  releaseName: podinfo
  serviceAccountName: flux-reconciler
  chart:
    spec:
      chart: podinfo
      version: 6.2.3
      sourceRef:
        kind: HelmRepository
        name: app-charts